name: Test Frontend & Backend

on:
  workflow_call:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install pnpm
        run: npm install -g pnpm
      - name: install frontend dependencies
        run: |
         cd app/doc-anonymisation
         pnpm install --frozen-lockfile

      - name: run backend tests
        run: |
         cd app/doc-anonymisation/src-tauri
         cargo test
      - name: run frontend tests
        run: |
         cd app/doc-anonymisation
         pnpm test --passWithNoTests
